# Generated by Django 2.0.3 on 2018-03-19 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('foods', '三餐'), ('snacks', '零食'), ('clothing', '服饰'), ('viaticum', '出行'), ('learn', '学习'), ('entertainment', '娱乐'), ('healthy', '健康'), ('telephone', '电话费'), ('medicine', '医疗'), ('others', '其他')], default='foods', max_length=20, verbose_name='消费原因')),
                ('cost', models.IntegerField(verbose_name='花费')),
                ('spent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
