# Generated by Django 2.0.3 on 2018-03-15 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 20, 15, 10, 857602), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 20, 15, 10, 863609), verbose_name='更新时间'),
        ),
    ]
